import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import FloatingButton from "@/app/components/FloatingButton";
import { Suspense } from "react";
import PageLoader from "@/app/components/PageLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MDM & 🧠D🌧️",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html lang="en" className="">
      <body className={`${inter.className}`}>
        <Navbar />
        <noscript>
          <p className="pt-6 text-xl text-red-600">
            You need to enable JavaScript to run this app.
          </p>
        </noscript>
        <Main>{children}</Main>
        <Footer />
      </body>
    </html>
  );
}

function Main({ children }: any) {
  return (
    <main className="p-1 mt-2 min-h-[82svh] md:min-h-[75svh]">
      <Suspense fallback={<PageLoader />}>{children}</Suspense>
      <FloatingButton />
    </main>
  );
}
